### ISSUE TITLE
Gradle version 4.3 not compatible anymore.

### ISSUE THREAD

**Issue by yibolisolace** [SolaceSamples/solace-samples-amqp-qpid-jms2#39] opened 2022-02-09 18:52 UTC
When I download and build the samples directly, I get errors:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '15.0.1'.

So I updated gradle to 6.7 which supports java 15, and now it says there are some deprecated methods in the samples:

Welcome to Gradle 6.7!

Here are the highlights of this release:
 - File system watching is ready for production use
 - Declare the version of Java your build requires
 - Java 15 support

For more details see https://docs.gradle.org/6.7/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\YiboLi\workspace\solace-samples-amqp-qpid-jms2-master\solace-samples-amqp-qpid-jms2-master\build.gradle' line: 37

* What went wrong:
A problem occurred evaluating root project 'solace-samples-amqp-qpid-jms2-master'.
> Could not find method leftShift() for arguments [build_159eqprh1o3fyj3pas6imoxgi$_run_closure4@43d47dc6] on task ':createAllStartScripts' of type org.gradle.api.DefaultTask.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s

**Comment by aaron-613** [comment] 2022-02-10 04:10
Hi @yibolisolace .  Thanks for flagging this, we're slowly making our way through all the samples to update them.

I've raised PR 40.  https://github.com/SolaceSamples/solace-samples-amqp-qpid-jms2/pull/40

Please checkout branch `39-upgrade-gradle` and verify it works for you on Java 15.

**Comment by Mrc0113** [comment] 2022-02-10 19:32
Re-opened temporarily until @yibolisolace confirms that it works with java 15

**Comment by aaron-613** [comment] 2022-02-11 10:41
Since Java 15 isn't an LTS release, I've tried using 17 with OpenJDK:
```
mkdir amqp-test-fix-temp
$ cd amqp-test-fix-temp/
$ git clone git@github.com:SolaceSamples/solace-samples-amqp-qpid-jms2.git .
Cloning into '.'...
Enter passphrase for key '/home/alee/.ssh/id_rsa':
remote: Enumerating objects: 885, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 885 (delta 1), reused 7 (delta 1), pack-reused 872
Receiving objects: 100% (885/885), 999.51 KiB | 883.00 KiB/s, done.
Resolving deltas: 100% (465/465), done.
$ sdk current java

Using java version 17.0.2-open
$ ./gradlew build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

BUILD SUCCESSFUL in 6s
10 actionable tasks: 10 executed
$ ls
CONTRIBUTING.md  LICENSE  NOTICE  README.md  _config.yml  build  build.gradle  gradle  gradlew  gradlew.bat  pom.xml  src
$ cd build/
$ ls
classes  generated  libs  scripts  staged  tmp
$ cd libs/
$ ls
solace-samples-amqp-qpid-jms2.jar
$ jar xf solace-samples-amqp-qpid-jms2.jar
$ ls
META-INF  com  solace-samples-amqp-qpid-jms2.jar
$ cd com/solace/samples/features/
$ ls
DurableTopicSubscriber.class
$ file DurableTopicSubscriber.class
DurableTopicSubscriber.class: compiled Java class data, version 61.0
```

So using SdkMan to use Java 17, this was built with no errors.  And then validated the class file was indeed made with JDK 17.

**Comment by Mrc0113** [comment] 2022-02-11 21:23
Closing since @aaron-613 confirmed.

**Closed by Mrc0113** 2022-02-11 21:23 UTC
